// src/popup/components/Item.vue
<template>
  <li
    role="button"
    tabindex="0"
    @click="openFile"
    @click.right.stop.prevent="openOverlay"
    class="download-item"
    :class="itemClasses"
  >
    <img :src="icon" class="icon" width="32" height="32" aria-hidden="true" alt="" />

    <div class="info">
      <div class="name">{{ filename }}</div>
      <div class="size">
        <div class="file-size">{{ filesize }}</div>
        <template v-if="showBar || showResume">
          <div class="dot">&CenterDot;</div>
          <div class="down-speed">{{ showResume ? 'Stopped' : downSpeed }}</div>
        </template>
      </div>
    </div>

    <div class="button-row">
      <!-- If the item can be resumed or paused, offer to toggle -->
      <button
        type="button"
        class="icon-button"
        v-if="showResume"
        @click.stop="resumeDownload"
      ><fa-icon icon="play" fixed-width /></button>
      <button
        type="button"
        class="icon-button"
        v-else-if="showPause"
        @click.stop="pauseDownload"
      ><fa-icon icon="pause" fixed-width /></button>

      <!-- If the item has been deleted or interrupted, offer to retry -->
      <button
        type="button"
        class="icon-button"
        v-if="showRetry"
        @click.stop="retryDownload"
      ><fa-icon icon="arrow-rotate-left" fixed-width /></button>

      <!-- If the item exists, offer to show its location on disk -->
      <button
        type="button"
        class="icon-button"
        v-if="showFolder"
        @click.stop="showFile"
      ><fa-icon icon="folder-blank" fixed-width /></button>
    </div>

    <ProgressBar
      v-if="showBar"
      :percent="percent"
      :gradient-start="barColor.start"
      :gradient-end="barColor.end"
    />

    <transition name="slide-fade">
      <ItemOverlay
        v-if="isOverlayOpen"
        @click.stop="closeOverlay"
      >
        <button
          type="button"
          class="icon-button link-button"
          @click="copyLink"
        ><fa-icon icon="link" fixed-width /></button>
        <button
          type="button"
          class="icon-button erase-button"
          @click="eraseFromList"
        ><fa-icon icon="xmark" fixed-width /></button>
      </ItemOverlay>
    </transition>

  </li>
</template>


<script lang="ts">
import { defineComponent, ref, computed, watch, toRefs, inject, Ref, PropType } from 'vue';
import { formatSize, computePercentage } from '@/common';
import { speedKey } from '../main';

import downloads = chrome.downloads;
import DownloadItem = downloads.DownloadItem;

import ProgressBar from './Bar.vue';
import ItemOverlay from './ItemOverlay.vue';


function useConditions(item: Ref<DownloadItem>) {

  const showResume = computed(() => item.value.canResume);
  const showPause = computed(() => item.value.state == 'in_progress');

  const showRetry = computed(() => item.value.state == 'interrupted' || !item.value.exists);

  const showFolder = computed(() => item.value.exists);

  const showBar = computed(() => item.value.state == 'in_progress' || item.value.canResume);

  return {
    showResume,
    showPause,
    showRetry,
    showFolder,
    showBar,
  }
}


function useFileInfo(item: Ref<DownloadItem>) {

  const { showBar: inProgress } = useConditions(item);
  const speeds = inject(speedKey);


  const filename = computed(() => {
    // Determine basename of file
    const path = item.value.filename;

    // Check if using '\' or '/' for Windows vs. *NIX
    const separator = path.indexOf('/') == -1 ? '\\' : '/';
    const filename = path.substring(path.lastIndexOf(separator) + 1);

    return filename.replace(/\.crdownload$/, '');
  });


  const percent = computed(() => {
    if (inProgress.value) {
      const { num, den } = computePercentage(item.value);
      return (den == 0) ? 0 : num / den;
    } else {
      return 1;
    }
  });


  const filesize = computed(() => {
    if (inProgress.value) {
      const { num, den } = computePercentage(item.value);
      return `${formatSize(num)} / ${formatSize(den)}`;
    } else {
      return formatSize(item.value.fileSize);
    }
  });


  const downSpeed = computed(() => {
    if (inProgress.value && speeds) {
      const speed = speeds.value[item.value.id];
      return `${formatSize(speed ?? -1)}/s`;
    } else {
      return `${formatSize(0)}/s`;
    }
  });


  // Defaults to a blank, 1x1, transparent `.gif` file (placeholder)
  const icon = ref('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');

  // Use a `watch` instead of a regular computed because `getFileIcon` is
  // asynchronous
  watch(() => item.value.id, async () => {
    const src = await new Promise<string>(resolve => {
      downloads.getFileIcon(item.value.id, { size: 32 }, resolve)
    });

    if (src) icon.value = src;
  }, { immediate: true });


  return {
    filename,
    filesize,
    downSpeed,
    percent,
    icon,
  };
}


export default defineComponent({
  name: 'Item',
  components: { ProgressBar, ItemOverlay },
  props: {
    item: {
      type: Object as PropType<DownloadItem>,
      required: true,
    }
  },
  emits: {
    erase: (id: number) => typeof id == 'number',
    retry: (url: string) => typeof url == 'string',
    overlay: null,
  },
  setup(props, { emit }) {
    const { item } = toRefs(props);

    const showFile = () => downloads.show(item.value.id);
    const openFile = () => {
      if (item.value.state == 'complete') downloads.open(item.value.id);
    }

    const pauseDownload = () => downloads.pause(item.value.id);
    const resumeDownload = () => downloads.resume(item.value.id);

    const retryDownload = () => emit('retry', item.value.url);
    const eraseFromList = () => emit('erase', item.value.id);
    const copyLink = () => navigator.clipboard.writeText(item.value.finalUrl);

    const isOverlayOpen = ref(false);
    const closeOverlay = () => isOverlayOpen.value = false;
    const openOverlay = () => {
      isOverlayOpen.value = true;
      emit('overlay');
    }

    const barColor = computed<{ start: string, end: string }>(() => {
      let cssVarName;

      if (item.value.paused) {
        cssVarName = 'paused';
      } else if (item.value.state == 'interrupted') {
        cssVarName = 'error';
      } else {
        cssVarName = 'normal';
      }

      return {
        start: `var(--progress-bar-${cssVarName}1)`,
        end: `var(--progress-bar-${cssVarName}2)`,
      };
    });

    const itemClasses = computed(() => ({
      'error': item.value.state == 'interrupted' || !item.value.exists,
      'overlay-open': isOverlayOpen.value,
    }));


    return {
      ...useConditions(item),
      ...useFileInfo(item),
      openFile,
      showFile,
      pauseDownload,
      resumeDownload,
      retryDownload,
      eraseFromList,
      copyLink,
      isOverlayOpen,
      closeOverlay,
      openOverlay,
      barColor,
      itemClasses,
    };

  },
});
</script>


<style lang="scss" scoped>
.download-item {
  height: 75px;
  padding: 0 14px;
  position: relative;

  border: 2px solid transparent;
  &:not(.overlay-open):hover {
    border-color: var(--item-border);
    &.error { border-color: var(--item-border-error); }
  }

  display: grid;
  grid-template-rows: 1fr;
  grid-template-columns: 48px minmax(0, 1fr) min-content;
  align-items: center;

  column-gap: 24px;

  background-color: var(--item-bg1);
  &:nth-child(2n+2) { background-color: var(--item-bg2); }

  cursor: pointer;
}

.icon {
  display: block;
  justify-self: center;
}

.info {
  display: flex;
  flex-flow: column nowrap;
  row-gap: 4px;
}

.name {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.size {
  display: flex;
  flex-flow: row nowrap;
  column-gap: 6px;
  font-size: 12px;
}

.dot {
  opacity: 0.75;
}

.erase-button {
  color: var(--button-warning-fg);
  --button-color: var(--button-warning-bg);
  --border-color: var(--button-warning-border);
}

.error {

  .icon, .name, .size {
    opacity: 0.45;
  }

}

::v-deep(.progress-bar) {
  inset: -2px;
  top: unset;
  width: calc(100% + 4px);
}

.slide-fade-enter-active, .slide-fade-leave-active {
  transition-duration: 125ms;
  transition-timing-function: ease-out;
  transition-property: transform, opacity;
}

.slide-fade-enter-from, .slide-fade-leave-to {
  transform: translateX(10px);
  opacity: 0;
}

.slide-fade-enter-to, .slide-fade-leave-from {
  transform: translateX(0);
  opacity: 1;
}
</style>

// src/popup/components/Item.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { bodyText } from 'shared';

  // A blank, 1x1, transparent .gif file to use as a placeholder 'src' attribute
  const emptyGIF = `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7`;

  // @ts-ignore beacuse TS doesn't seem to recognize experimental new UA testing
  const showIn = (navigator.userAgentData) // @ts-ignore next line too
    ? /mac/i.test(navigator.userAgentData.platform) ? 'macos' : 'folder'
    : /mac/i.test(navigator.platform) ? 'macos' : 'folder';

  const folderOrFinder = bodyText(`location_${showIn}`);

  const dispatch = createEventDispatcher<{
    'erase': number,  // id
    'retry': string,  // url
  }>();

  // ===== Props =====

  export let item: chrome.downloads.DownloadItem;

  // ===== Methods =====

  const basename = (path: string): string => {
    // Check if using '\' or '/' for Windows vs. *nix
    const separator = path.indexOf('/') == -1 ? '\\' : '/';
    const filename = path.substring(path.lastIndexOf(separator) + 1);
    return filename.replace(/\.crdownload$/, '');
  }

  // https://stackoverflow.com/a/18650828/10549827
  const formatSize = (bytes: number): string => {
    if (bytes == -1) return '? Bytes';
    else if (bytes == 0) return '0 Bytes';

    const k = 1000;
    const s = [ 'Bytes', 'KB', 'MB', 'GB', 'TB' ];
    const i = Math.floor(Math.log10(bytes) / Math.log10(k));
    const p = i && 2; // 0 decimals if index is 0; no decimals for 'Bytes'

    return `${(bytes / Math.pow(k, i)).toFixed(p)} ${s[i]}`;
  }

  const open = () => chrome.downloads.open(item.id);
  const show = () => chrome.downloads.show(item.id);
  const retry = () => dispatch('retry', item.url);
  const erase = () => dispatch('erase', item.id);

  // ===== Reactive =====

  let title: string = '';
  let bytes: string = '? Bytes';
  let image: string = emptyGIF;
  let state: string = '';

  $: title = basename(item.filename);
  $: state = !item.exists ? 'deleted' : item.state.replaceAll('_', '-');

  $: if (item.state == 'in_progress') {
    bytes = `${formatSize(item.bytesReceived)} / ${formatSize(item.totalBytes)}`
  } else {
    bytes = formatSize(item.fileSize);
  }

  $: chrome.downloads.getFileIcon(item.id, { size: 32 }, src => {
    image = (src || emptyGIF);
  });

  let barRole: string | undefined = undefined;
  let valueMin: number | undefined = undefined;
  let valueMax: number | undefined = undefined;
  let valueNow: number | undefined = undefined;

  $: if (state == 'in-progress') {
    barRole = 'progressbar';
    valueMin = 0;
    valueMax = 0;
    valueNow = item.bytesReceived / item.totalBytes * 100;
  } else {
    barRole = valueMin = valueMax = valueNow = undefined;
  }
</script>

<li class="download { state }" role="button" tabindex="0" on:click={open}>
  <img src={image} width="32" height="32" alt="" aria-hidden="true" />

  <div class="body">

    <span class="title">{ title }</span>

    <div
      class="progress"
      class:hidden={item.state != 'in_progress'}
      role={barRole}
      aria-valuemin={valueMin}
      aria-valuemax={valueMax}
      aria-valuenow={valueNow}
    >
      <div class="bar" style="width: {valueNow}%"></div>
    </div>

    <div class="controls">
      <span class="file-size">{ bytes }</span>
      {#if item.exists}
        <span class="action" role="button" tabindex="0" on:click|stopPropagation={show}>
          { bodyText('show_in', folderOrFinder) }
        </span>
      {:else if state != 'complete'} <!-- does not exist and also not 'complete'; deleted -->
        <span class="action" role="button" tabindex="0" on:click|stopPropagation={retry}>
          { bodyText('download_again') }
        </span>
      {/if}
      <span class="action" role="button" tabindex="0" on:click|stopPropagation={erase}>
        { bodyText('erase_item') }
      </span>
    </div>

  </div>
</li>

<style lang="scss">
.download {
  display: grid;
  // https://css-tricks.com/preventing-a-grid-blowout/
  grid-template-columns: auto minmax(0, 1fr);
  column-gap: 0.95em;

  --status-color: transparent; // fallback

  &.paused { --status-color: #ffcc00; }
  &.complete { --status-color: #65ce46; }
  &.in-progress { --status-color: #52b4ff; }
  &.interrupted, &.deleted { --status-color: #f77878; }

  border-radius: 0 0.25em 0.25em 0;
  border: 0.20em solid transparent;
  border-left: 0.35em solid var(--status-color) !important;

  margin-bottom: 0.15em;

  cursor: pointer;

  >img {
    align-self: flex-start;
    justify-self: flex-end;
    margin: 0.85em 0 0.35em 0.90em;
  }

  .body {
    padding: 0.85em 1.25em 0.90em 0;
    height: 2.75rem;

    display: flex;
    flex-flow: column nowrap;
    justify-content: space-between;
  }

  .title {
    font-weight: bold;
    color: var(--color-title);

    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
  }

  &.interrupted, &.deleted {
    >img { filter: grayscale(1); }

    .title {
      opacity: 0.75;
      text-decoration-line: line-through;
    }
  }

  .progress {
    height: 0.25em;

    position: relative;
    align-self: stretch;

    .bar {
      position: absolute;
      top: 0; left: 0;
      height: 100%;

      background-color: var(--status-color);
    }
  }

  .controls {
    display: flex;
    flex-flow: row nowrap;
    >:first-child { margin-left: 0; }
    >:last-child { margin-right: 0; }
  }

  .file-size {
    margin-right: auto;
    color: #999;
  }

  .action {
    margin: 0 0.75em;
    color: var(--color-action);
    padding: 0.10em 0.10em 0;
    border-bottom: 0.10em solid transparent;

    &:hover, &:active {
      color: var(--color-action-hover);
      border-bottom-color: var(--color-background-accent);
    }

    &:active {
      border-bottom-color: var(--color-background-accent-hover);
    }
  }

  background-color: #ffffff;
  &:nth-child(2n+1) { background-color: #f8f8f8; }

  &:hover, &:active {
    background-color: var(--color-background-hover);
    border-color: var(--color-border-hover);
    .title { color: var(--color-title-hover); }
  }

  &:active { background-color: var(--color-background-active); }
}

.hidden {
  opacity: 0;
  visibility: hidden;
}
</style>
