// src/popup/Item.vue
<template>
  <li
    role="button"
    tabindex="0"
    @click="openFile"
    class="download-item"
    :class="{ error: item.state == 'interrupted' || !item.exists }"
  >
    <img :src="icon" class="icon" width="32" height="32" aria-hidden="true" alt="" />

    <div class="info">
      <div class="name">{{ filename }}</div>
      <div class="size">{{ filesize }}</div>
    </div>

    <div class="buttons">
      <!-- If the item can be resumed or paused, offer to toggle -->
      <button
        type="button"
        v-if="item.canResume"
        @click.stop="resumeDownload"
      ><fa-icon icon="play" fixed-width /></button>
      <button
        type="button"
        v-else-if="item.state == 'in_progress'"
        @click.stop="pauseDownload"
      ><fa-icon icon="pause" fixed-width /></button>

      <!-- If the item has been deleted or interrupted, offer to retry -->
      <button
        type="button"
        v-if="item.state == 'interrupted' || !item.exists"
        @click.stop="retryDownload"
      ><fa-icon icon="arrow-rotate-left" fixed-width /></button>

      <!-- If the item exists, offer to show its location on disk -->
      <button
        type="button"
        v-if="item.exists"
        @click.stop="showFile"
      ><fa-icon icon="folder-blank" fixed-width /></button>
    </div>

    <ProgressBar
      v-if="item.state == 'in_progress' || item.canResume"
      :percent="item.bytesReceived / item.totalBytes"
      gradient-start="#14415A"
      gradient-end="#00A3FF"
    />

  </li>
</template>


<script lang="ts">
import { defineComponent, PropType, ref, computed, watch, toRefs, Ref } from 'vue';
import { formatSize, isMac } from '@/common';

import downloads = chrome.downloads;
import DownloadItem = downloads.DownloadItem;
import bodyText = chrome.i18n.getMessage;

import ProgressBar from './Bar.vue';


enum ItemState {
  Valid,
  Error,
  Progress,
}


function useFileInfo(item: Ref<DownloadItem>) {

  const filename = computed(() => {
    // Determine basename of file
    const path = item.value.filename;

    // Check if using '\' or '/' for Windows vs. *NIX
    const separator = path.indexOf('/') == -1 ? '\\' : '/';
    const filename = path.substring(path.lastIndexOf(separator) + 1);

    return filename.replace(/\.crdownload$/, '');
  });


  const filesize = computed(() => {
    if (item.value.state == 'in_progress') {
      const a = formatSize(item.value.bytesReceived);
      const b = formatSize(item.value.totalBytes);
      return `${a} / ${b}`;
    } else {
      return formatSize(item.value.fileSize);
    }
  });

  // Defaults to a blank, 1x1, transparent `.gif` file (placeholder)
  const icon = ref('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');

  watch(item, async () => {
    const src = await new Promise<string>(resolve => {
      downloads.getFileIcon(item.value.id, { size: 32 }, resolve)
    });

    if (src) icon.value = src;
  }, {
    immediate: true
  });


  return {
    filename,
    filesize,
    icon,
  };
}


export default defineComponent({
  name: 'Item',
  components: { ProgressBar },
  props: {
    item: {
      type: Object as PropType<DownloadItem>,
      required: true,
    }
  },
  emits: {
    erase: (id: number) => typeof id == 'number',
    retry: (url: string) => typeof url == 'string',
  },
  setup(props, { emit }) {
    const { item } = toRefs(props);
    const folderOrFinder = bodyText(`location_${isMac ? 'macos' : 'folder'}`);

    const openFile = () => downloads.open(item.value.id);
    const showFile = () => downloads.show(item.value.id);

    const pauseDownload = () => downloads.pause(item.value.id);
    const resumeDownload = () => downloads.resume(item.value.id);

    const retryDownload = () => emit('retry', item.value.url);
    const eraseFromList = () => emit('erase', item.value.id);

    const state = computed<ItemState>(() => {
      if (!item.value.exists) return ItemState.Error;

      switch (item.value.state) {
        case 'complete': return ItemState.Valid;
        case 'in_progress': return ItemState.Progress;
        case 'interrupted': return ItemState.Error;
      }
    });

    const barColor = computed(() => {
      if (item.value.state == 'in_progress') {
        if (item.value.paused) return 'paused';
        else return 'regular';
      } else if (item.value.state == 'interrupted') {
        return 'error';
      }
    });


    return {
      folderOrFinder,
      ...useFileInfo(item),
      openFile,
      showFile,
      pauseDownload,
      resumeDownload,
      retryDownload,
      eraseFromList,
      state,
      barColor,
      ItemState,
    };

  },
});
</script>


<style lang="scss" scoped>
.download-item {
  height: 75px;
  padding: 0 14px;
  position: relative;

  border: 2px solid transparent;
  &:hover { border-color: var(--accent1); }

  display: grid;
  grid-template-rows: 1fr;
  grid-template-columns: 48px minmax(0, 1fr) min-content;
  align-items: center;

  column-gap: 24px;

  background-color: var(--item-bg1);
  &:nth-child(2n+2) { background-color: var(--item-bg2); }

  cursor: pointer;
}

.icon {
  display: block;
  justify-self: center;
}

.info {
  display: flex;
  flex-flow: column nowrap;
  row-gap: 4px;
}

.name {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.size {
  font-size: 12px;
}

.buttons {

  display: flex;
  flex-flow: row nowrap;
  justify-content: flex-end;
  column-gap: 14px;

  button {
    width: 40px;
    height: 40px;
    border-radius: 50%;

    border: 2px solid transparent;
    &:hover { border-color: var(--accent2); }

    margin: 0;
    padding: 2px;

    display: flex;
    align-items: center;
    justify-content: center;

    color: inherit;
    background-color: var(--button-bg1);

    cursor: pointer;
  }
}

.error {

  .icon, .name, .size {
    opacity: 0.45;
  }

}

::v-deep(.progress-bar) {
  inset: -1px;
  top: unset;
}
</style>

// src/popup/components/Item.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { bodyText } from 'shared';

  // A blank, 1x1, transparent .gif file to use as a placeholder 'src' attribute
  const emptyGIF = `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7`;

  // @ts-ignore beacuse TS doesn't seem to recognize experimental new UA testing
  const showIn = (navigator.userAgentData) // @ts-ignore next line too
    ? /mac/i.test(navigator.userAgentData.platform) ? 'macos' : 'folder'
    : /mac/i.test(navigator.platform) ? 'macos' : 'folder';

  const folderOrFinder = bodyText(`location_${showIn}`);

  const dispatch = createEventDispatcher<{
    'erase': number,  // id
    'retry': string,  // url
  }>();

  // ===== Props =====

  export let item: chrome.downloads.DownloadItem;

  // ===== Methods =====

  const basename = (path: string): string => {
    // Check if using '\' or '/' for Windows vs. *nix
    const separator = path.indexOf('/') == -1 ? '\\' : '/';
    const filename = path.substring(path.lastIndexOf(separator) + 1);
    return filename.replace(/\.crdownload$/, '');
  }

  // https://stackoverflow.com/a/18650828/10549827
  const formatSize = (bytes: number): string => {
    if (bytes == -1) return '? Bytes';
    else if (bytes == 0) return '0 Bytes';

    const k = 1000;
    const s = [ 'Bytes', 'KB', 'MB', 'GB', 'TB' ];
    const i = Math.floor(Math.log10(bytes) / Math.log10(k));
    const p = i && 2; // 0 decimals if index is 0; no decimals for 'Bytes'

    return `${(bytes / Math.pow(k, i)).toFixed(p)} ${s[i]}`;
  }

  const open = () => chrome.downloads.open(item.id);
  const show = () => chrome.downloads.show(item.id);
  const retry = () => dispatch('retry', item.url);
  const erase = () => dispatch('erase', item.id);

  // ===== Reactive =====

  let title: string = '';
  let bytes: string = '? Bytes';
  let image: string = emptyGIF;
  let state: string = '';

  $: title = basename(item.filename);
  $: state = !item.exists ? 'deleted' : item.state.replaceAll('_', '-');

  $: if (item.state == 'in_progress') {
    bytes = `${formatSize(item.bytesReceived)} / ${formatSize(item.totalBytes)}`
  } else {
    bytes = formatSize(item.fileSize);
  }

  $: chrome.downloads.getFileIcon(item.id, { size: 32 }, src => {
    image = (src || emptyGIF);
  });

  let barRole: string | undefined = undefined;
  let valueMin: number | undefined = undefined;
  let valueMax: number | undefined = undefined;
  let valueNow: number | undefined = undefined;

  $: if (state == 'in-progress') {
    barRole = 'progressbar';
    valueMin = 0;
    valueMax = 0;
    valueNow = item.bytesReceived / item.totalBytes * 100;
  } else {
    barRole = valueMin = valueMax = valueNow = undefined;
  }
</script>

<li class="download { state }" role="button" tabindex="0" on:click={open}>
  <img src={image} width="32" height="32" alt="" aria-hidden="true" />

  <div class="body">

    <span class="title">{ title }</span>

    <div
      class="progress"
      class:hidden={item.state != 'in_progress'}
      role={barRole}
      aria-valuemin={valueMin}
      aria-valuemax={valueMax}
      aria-valuenow={valueNow}
    >
      <div class="bar" style="width: {valueNow}%"></div>
    </div>

    <div class="controls">
      <span class="file-size">{ bytes }</span>
      {#if item.exists}
        <span class="action" role="button" tabindex="0" on:click|stopPropagation={show}>
          { bodyText('show_in', folderOrFinder) }
        </span>
      {:else if state != 'complete'} <!-- does not exist and also not 'complete'; deleted -->
        <span class="action" role="button" tabindex="0" on:click|stopPropagation={retry}>
          { bodyText('download_again') }
        </span>
      {/if}
      <span class="action" role="button" tabindex="0" on:click|stopPropagation={erase}>
        { bodyText('erase_item') }
      </span>
    </div>

  </div>
</li>

<style lang="scss">
.download {
  display: grid;
  // https://css-tricks.com/preventing-a-grid-blowout/
  grid-template-columns: auto minmax(0, 1fr);
  column-gap: 0.95em;

  --status-color: transparent; // fallback

  &.paused { --status-color: #ffcc00; }
  &.complete { --status-color: #65ce46; }
  &.in-progress { --status-color: #52b4ff; }
  &.interrupted, &.deleted { --status-color: #f77878; }

  border-radius: 0 0.25em 0.25em 0;
  border: 0.20em solid transparent;
  border-left: 0.35em solid var(--status-color) !important;

  margin-bottom: 0.15em;

  cursor: pointer;

  >img {
    align-self: flex-start;
    justify-self: flex-end;
    margin: 0.85em 0 0.35em 0.90em;
  }

  .body {
    padding: 0.85em 1.25em 0.90em 0;
    height: 2.75rem;

    display: flex;
    flex-flow: column nowrap;
    justify-content: space-between;
  }

  .title {
    font-weight: bold;
    color: var(--color-title);

    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
  }

  &.interrupted, &.deleted {
    >img { filter: grayscale(1); }

    .title {
      opacity: 0.75;
      text-decoration-line: line-through;
    }
  }

  .progress {
    height: 0.25em;

    position: relative;
    align-self: stretch;

    .bar {
      position: absolute;
      top: 0; left: 0;
      height: 100%;

      background-color: var(--status-color);
    }
  }

  .controls {
    display: flex;
    flex-flow: row nowrap;
    >:first-child { margin-left: 0; }
    >:last-child { margin-right: 0; }
  }

  .file-size {
    margin-right: auto;
    color: #999;
  }

  .action {
    margin: 0 0.75em;
    color: var(--color-action);
    padding: 0.10em 0.10em 0;
    border-bottom: 0.10em solid transparent;

    &:hover, &:active {
      color: var(--color-action-hover);
      border-bottom-color: var(--color-background-accent);
    }

    &:active {
      border-bottom-color: var(--color-background-accent-hover);
    }
  }

  background-color: #ffffff;
  &:nth-child(2n+1) { background-color: #f8f8f8; }

  &:hover, &:active {
    background-color: var(--color-background-hover);
    border-color: var(--color-border-hover);
    .title { color: var(--color-title-hover); }
  }

  &:active { background-color: var(--color-background-active); }
}

.hidden {
  opacity: 0;
  visibility: hidden;
}
</style>
